### PR TITLE
Cleanup and added some tests.

### PR DESCRIPTION
**Pull request by piotrooo**
I created the first PR with changes and cleanup proposals. Let me know if something is bad or not in your style.

PS. As you can see I wrote one test in BDD style, I prefer that kind of tests, because when I read a test name I know what is class responsibility. If it's not your preferable style let me know.

### CODE REVIEW

**Comment by blong14** [comment]
Overall, I think this seems fine. My only suggestion would be to make sure all new code is compatible with PHP version 5.6. #46 adds docker and some instructions to make version testing easier locally.

**Comment by piotrooo** [comment]
@blong14 any reasons for support this version? End of support at the end of tnę year.
When this linked PR goes into master?

**Comment by blong14** [comment]
@piotrooo checkout #11 for the history of 5.6 support. I "think" #46 is ready for merge once signed off on. Currently, on that branch travis fails due to lint failures. Linting is one of the features added in that branch. Do you mind taking a look at the travis file on that branch? You may have some opinions how linting should work.

**Comment by piotrooo** [comment]
@blong14 I don't get why PHP 5.6 is required to 'merege' it with a jaeger tracing?

I'm not familiar with the phpcs I was always using a php-cs-fixer. 
This is how I imagine that could work:
- dev write a not well formatted code
- Travis runs that commit and Mark its as failed
- dev run fixer with our config (I love defaults, maybe this is a good way?)
- commit fixed files (maybe squash a commit?)

**Comment by jonahgeorge** [comment]
LGTM. Thanks for the contribution!

**Comment by jonahgeorge** [comment]
@piotrooo Regarding PHP 5.6, there appears to be no requirements by anyone from the Jaeger org; however, there's been emphasis put on supporting 5.6 in the discussions are which library to standardize on. If those talks continue till the end of the year, we might just wait out the PHP 5.6 EOL.

**Comment by piotrooo** [comment]
@jonahgeorge it's important to know which version of PHP we will be supporting, because of types and other language features. It's hard to refactor code without knowledge about language level ;(

**Pull request merged**
