### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by egor-muindor**
I think it should work. I am not sure how true I did everything, so if I get feedback, then I will try to correct the remarks.

I fixed tests for compatibility with PHPUnit 9+, but the methods I used to replace obsolete ones are not in PHPUnit 6, so I removed its support.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Hello @egor-muindor,

I will keep this open for a some (short) time to allow other contributors a chance to speak up, and to take a fresh look at it later. We'll need also PHP 8 support, so I plan migrate CI to GitHub Actions to be able run tests using PHP 8. But at the moment it seems good to me. Thank you for the contributing, and for helping make jaeger-client-php better.

**Comment by sergeyklay** [comment]
@egor-muindor This branch has conflicts that must be resolved. Also note we're use GitHub Actions now thank to @m1x0n, so you'll need to enable PHP 8 here https://github.com/jonahgeorge/jaeger-client-php/blob/fb4d267f6b7d46fe62fcc7d8ab8f1c9971eaa8de/.github/workflows/main.yaml#L9-L11

**Comment by egor-muindor** [comment]
I fixed the conflict and added PHP 8 to Github Actions workflow.

**Review by sergeyklay — APPROVED** [review]

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
