### PR TITLE
Fix large hex -> int64 trace/span id extraction

### PR DESCRIPTION
**Pull request by jaredru**
PHP utilizes signed ints internally, which means the largest integer value it can represent on a 64-bit system is `9223372036854775807`. However, `base_convert` converts values to arbitrarily large _positive_ numbers, meaning incoming trace ids larger than `7fffffffffffffff` are converted to string representations of numbers larger than `9223372036854775807`.

`TBinaryProtocol`, when building a binary Thrift representation of a Span, [performs bitwise operations](https://github.com/packaged/thrift/blob/8af3f4c0388319f65a2522844d80d8ded60d211b/src/Thrift/Protocol/TBinaryProtocol.php#L195-L197) on the trace ids, implicitly casting them to `int` and capping the value at `9223372036854775807`. The consequence is any extracted trace id larger than `7fffffffffffffff` is sent to the agent as `7fffffffffffffff`.

This change updates `TextCodec` extraction to split the hex span ids into high and low values, convert them to integers separately, and manually combine them into a proper, signed int. These values are then handled properly by the Thrift package.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@jaredru Could you please fixe these code style issues:
```
FILE: ...ild/jonahgeorge/jaeger-client-php/src/Jaeger/Codec/TextCodec.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 35 | ERROR | [x] Opening brace should be on a new line
    |       |     (Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine)
 42 | ERROR | [x] Expected 1 space after comma in function call; 2
    |       |     found
    |       |     (Generic.Functions.FunctionCallArgumentSpacing.TooMuchSpaceAfterComma)
 42 | ERROR | [x] Expected 1 space after comma in function call; 2
    |       |     found
    |       |     (Generic.Functions.FunctionCallArgumentSpacing.TooMuchSpaceAfterComma)
----------------------------------------------------------------------
```

**Comment by sergeyklay** [comment]
@jaredru Looks good to me but I'm not sure why do we need a function outside the class scope in the same file. Could you elaborate on that?

**Comment by jonahgeorge** [comment]
Two things to keep in mind:
- The use of [`Phlib\base_convert`](https://github.com/phlib/base_convert) already
- That Jaeger will need to support 128-bit number in the [(near) future](https://github.com/jaegertracing/jaeger/issues/858)

**Comment by jaredru** [comment]
> I'm not sure why do we need a function outside the class scope in the same file. Could you elaborate on that?

There's no strong reason. It doesn't need access to any class internals and felt more like a library/utility function to me than something specific to the class. I'm happy to move it if you'd prefer.

> That Jaeger will need to support 128-bit trace IDs in the (near) future

Yeah, I primarily just wanted to get the existing 64-bit extraction working. However, I also have a [branch with 128-bit support](https://github.com/jonahgeorge/jaeger-client-php/compare/master...jaredru:v0.3.0-128bit) that I've been testing locally and seems to be working. It's a bigger change but also moves in the right long-term direction. Let me know if you'd like me to open a PR for that instead of this.

**Comment by sergeyklay** [comment]
@jaredru Let's make `hexToInt64` as private class member.

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
