### PR TITLE
Upgrade opentracing to 1.0

### PR DESCRIPTION
**Pull request by limingxinleo**

### CODE REVIEW

**Comment by limingxinleo** [comment]
@sergeyklay Hi, opentracing released v1.0.0 🚀

The PHPUnit for Hyperf was broken, please deal with it as soon as possible

Thanks very much.

**Comment by limingxinleo** [comment]
https://github.com/hyperf/hyperf/pull/3007

**Comment by Reasno** [comment]
@sergeyklay could you take a look at this?

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you!

**Comment by sergeyklay** [comment]
Released https://github.com/jonahgeorge/jaeger-client-php/releases/tag/v1.0.0

**Pull request merged**
